name: Elixir CI

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main, ci-test ]

env:
  MIX_ENV: test

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [ '1.18.1', '1.18.3', 'latest' ]
        otp:    [ '25.3.1', '26.2.0', '27.3.0', '27.3.3' ]
    name: Build & Test (OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }})
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version:     ${{ matrix.otp }}
      - uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
            ${{ runner.os }}-${{ matrix.otp }}-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force --if-missing
          mix local.hex   --force
          mix deps.get
      - run: mix compile --warnings-as-errors
      - name: Check format
        if: matrix.otp == '27.3.3' && matrix.elixir == 'latest'
        run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix dialyzer
      - run: mix test

      # === Generate and Upload Coverage ===
      - name: Generate LCOV report
        run: mix coveralls.lcov   # writes cover/lcov.info :contentReference[oaicite:13]{index=13}
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2   # v2.3.6 :contentReference[oaicite:14]{index=14}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}
          build-number: ${{ github.run_id }}    # stable build ID across jobs :contentReference[oaicite:15]{index=15}
          file: cover/lcov.info
          format: lcov

      - run: mix docs
      - uses: actions/upload-artifact@v4
        with:
          name: doc-${{ matrix.otp }}-${{ matrix.elixir }}
          path: doc

  coveralls_finalize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Finalize Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          build-number: ${{ github.run_id }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      DEPLOY_OTP:    '27.3.3'
      DEPLOY_ELIXIR: 'latest'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: doc-${{ env.DEPLOY_OTP }}-${{ env.DEPLOY_ELIXIR }}
          path: doc
      - run: |
          cd doc
          git init --initial-branch gh-pages
          git remote add origin git@github.com:BartOtten/routex.git
          git config user.name  "Bart Otten"
          git config user.email "bart.otten85@gmail.com"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.GH_PAGES_SSH }}"
          git add .
          git commit -m "mix docs"
          git push --force origin gh-pages
